### ISSUE TITLE
pyiceberg produces invalid avro if a partition name has an emoji (any non-alphanumeric character I guess, including dots or starting with digits)

### ISSUE THREAD

**Issue by nvartolomei** [apache/iceberg-python#2123]
### Apache Iceberg version

None

### Please describe the bug 🐞

Example schema:

```python
# Define schema with nested structure and timestamp
schema = Schema(
    NestedField(id=1, name="name", field_type=StringType(), required=True),
    NestedField(id=2, name="😎", field_type=StringType(), required=False),
    NestedField(id=5, name="timestamp", field_type=TimestampType(), required=True),
)

partition_spec = PartitionSpec(
    PartitionField(
        source_id=2,
        field_id=1001,
        transform=IdentityTransform(),
        name="😎",)
)
```

Write some data then try to read it with DuckDB or simply:

```sh
avrocat /home/nv/src/pyiceberg-example/warehouse/default.db/nested_table/metadata/afc5e55c-6dd2-4875-841c-410108fccf8e-m0.avro | jq .
```
```
Error opening /home/nv/src/pyiceberg-example/warehouse/default.db/nested_table/metadata/afc5e55c-6dd2-4875-841c-410108fccf8e-m0.avro:
  Cannot parse file header: Invalid Avro identifier
```

### Willingness to contribute

- [ ] I can contribute a fix for this bug independently
- [ ] I would be willing to contribute a fix for this bug with guidance from the Iceberg community
- [x] I cannot contribute a fix for this bug at this time

**Comment by kevinjqliu** [comment]
😎😎😎 Thanks for reporting this issue! 

It looks like this is due to the avro naming convention 


https://avro.apache.org/docs/1.11.1/specification/#names
```
The name portion of the fullname of named types, record field names, and enum symbols must:

start with [A-Za-z_]
subsequently contain only [A-Za-z0-9_]
```

so 😎 is not a valid field name.

We should validate the avro naming convention

**Comment by kevinjqliu** [comment]
we already have this helper function 

https://github.com/apache/iceberg-python/blob/89e71c36f26d1f3da48090ddfa137a698e2a06fc/pyiceberg/schema.py#L1364-L1374

**Comment by kris-gaudel** [comment]
Could I be assigned this issue please

**Comment by kevinjqliu** [comment]
@kris-gaudel done! looking forward to the PR

**Comment by kris-gaudel** [comment]
I see there's a function to sanitize field names called `sanitize_column_names`, will this function be deprecated if the new behavior is to reject field names that don't already fit the Avro standard? If so should I remove this test?

I was thinking instead of rejecting the name, we could sanitize it in the constructor

https://github.com/apache/iceberg-python/blob/e937f6a1811c9e090552a4ae2015a8032e7ea910/tests/test_schema.py#L440-L441

**Comment by nvartolomei** [comment]
@kevinjqliu if you’ll use this sanitization function on emojis, in particular on a 4 byte one, the Python and Java implementation will encode the field names differently. That’s because Python encodes the whole utf-8 point at a time where’s Java will encode it as 2 2-byte chars (it uses utf-16 internally so 16 byte chars). Can this break anything?

For 😎:

- Java encodes one UTF-16 char at a time: `_xD83D_xDE0E`.
- Python encodes 4 bytes at a time: `_x1F60E`.

_I’m not working on a PR for this. Discovered this while investigating the behaviour for my custom iceberg implementation._

**Comment by kris-gaudel** [comment]
@kevinjqliu Would be great to hear your thoughts on this

**Comment by kevinjqliu** [comment]
Thanks for the note @nvartolomei, thats a great point. 

i found the answer from the java reference implementation 
https://github.com/apache/iceberg/blob/85cc58aa8acda999926809b3c67bbc3452689490/core/src/main/java/org/apache/iceberg/avro/TypeToSchema.java#L116-L129

we should match the behavior for `validAvroName`, `sanitize`, and `ICEBERG_FIELD_NAME_PROP`

this is also used on the read side
https://github.com/apache/iceberg/blob/85cc58aa8acda999926809b3c67bbc3452689490/core/src/main/java/org/apache/iceberg/avro/BuildAvroProjection.java#L98-L122

And these are great tests to include
https://github.com/apache/iceberg/blob/85cc58aa8acda999926809b3c67bbc3452689490/core/src/test/java/org/apache/iceberg/avro/TestSchemaConversions.java#L334-L358

**Comment by kris-gaudel** [comment]
I'll close my other PR and raise another one implementing this approach

**Comment by kevinjqliu** [comment]
thanks @kris-gaudel let me know if theres anything i can help with. 

https://github.com/apache/iceberg-python/pull/83 was the previous fix for the avro column sanitization

**Comment by nvartolomei** [comment]
I’m still confused about it and would love to see a test (e2e) showing a
bug.

The Avro projection thingy seems to be related to reading avro files and
not parquets. Wonder if it’s some sort of legacy. Parquet doesn’t have
issues with special chars in field names. We use field ids rather than the
names too. 🤷‍♂️

**Comment by kevinjqliu** [comment]
#2241 shows that we're already using the right sanitization logic for column names. And i also tested locally with `😎`

i wonder if its with `ICEBERG_FIELD_NAME_PROP` OR `PartitionField`

**Comment by kevinjqliu** [comment]
To answer the original issue, i think instead of rejecting invalid avro identifiers in field names, we should (and already do) sanitize the name, just like the java reference implementation

**Comment by kevinjqliu** [comment]
Since we can validate that the field names are sanitized properly with #2241, im inclined to move this out of the 0.10 milestone

**Comment by sungwy** [comment]
Hi @nvartolomei - thanks for raising this issue and thanks for jumping into look into this @kevinjqliu and @kris-gaudel 

I think if this bug is indeed there, it's a rather serious issue since it would suggest that the field names produced from each language library (Python vs Java) is different, and hence would lead to issues in data accessibility.

I've tried replicating this issue with '😎' character and read it using duckdb, and unfortunately I was not able to replicate the issue: https://github.com/apache/iceberg-python/pull/2243

@nvartolomei Could you demonstrate how to replicate this issue? Is the e2e test I've added on that PR, and the one that @kevinjqliu mirrored from Java enough to demonstrate that the field name is sanitized in a duckdb compatible format?

**Comment by kevinjqliu** [comment]
thanks sung for the repro. i was curious about whether its due to the different duckdb versions. I used duckdb 1.0.0 in https://github.com/kevinjqliu/iceberg-python/pull/16 which was [released last june](https://duckdb.org/release_calendar.html). Seems like that is not the issue either

**Comment by nvartolomei** [comment]
Maybe it is fixed in main branch?

```toml
[project]
name = "pyiceberg-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pyiceberg-core>=0.5.1",
    "pyiceberg[pyarrow,sql-sqlite]>=0.9.1",
]
```

```py
#!/usr/bin/env python3

import os
from datetime import datetime

import pyarrow as pa
from pyiceberg.catalog import load_catalog
from pyiceberg.partitioning import PartitionField, PartitionSpec
from pyiceberg.schema import NestedField, Schema
from pyiceberg.transforms import IdentityTransform
from pyiceberg.types import StringType


def local_catalog():
    # Create a local catalog
    warehouse_path = os.path.join(os.getcwd(), "warehouse")
    os.makedirs(warehouse_path, exist_ok=True)

    return load_catalog(
        "local_catalog",
        **{
            "type": "sql",
            "uri": "sqlite:///iceberg_catalog.db",
            "warehouse": warehouse_path,
        },
    )


def main():
    catalog = local_catalog()

    # Create namespace if it doesn't exist
    if ("default", ) not in catalog.list_namespaces():
        catalog.create_namespace("default")

    # Table identifier
    table_identifier = "default.nested_table"

    # Define schema with nested structure and timestamp
    schema = Schema(
        NestedField(id=1, name="name", field_type=StringType(), required=True),
        NestedField(id=2, name="😎", field_type=StringType(), required=False),
    )

    partition_spec = PartitionSpec(
        PartitionField(
            source_id=2,
            field_id=1001,
            transform=IdentityTransform(),
            name="😎",
        ))

    table = catalog.create_table(identifier=table_identifier,
                                 schema=schema,
                                 partition_spec=partition_spec)

    print(
        f"Table {table.name()} created successfully with partition spec: {table.spec()}"
    )

    table.append(
        pa.Table.from_pylist([{
            "name": "Foo",
            "😎": "Cool Foo",
            "timestamp": datetime(2023, 10, 1, 12, 0, 0)
        }, {
            "name": "Bar",
            "😎": "Cool Bar",
            "timestamp": datetime(2023, 10, 2, 14, 30, 0)
        }],
                             schema=table.schema().as_arrow()))


if __name__ == "__main__":
    main()
```

```sh
duckdb --version
#  v1.3.1 (Ossivalis) 2063dda3e6

uv run nested_partition_field.py
# Table ('default', 'nested_table') created successfully with partition spec: [
#   1000: 😎: identity(2)
# ]
# Location /home/nv/src/pyiceberg-example/warehouse/default.db/nested_table
# Writing file to /home/nv/src/pyiceberg-example/warehouse/default.db/nested_table/data/%F0%9F%98%8E=Cool+Bar/00000-1-621d9a51-3b81-4c83-8a23-5af2c568c6d1.parquet
# Writing file to /home/nv/src/pyiceberg-example/warehouse/default.db/nested_table/data/%F0%9F%98%8E=Cool+Foo/00000-0-621d9a51-3b81-4c83-8a23-5af2c568c6d1.parquet

printf "SELECT * FROM iceberg_scan('%s')" $(ls --color=never warehouse/default.db/nested_table/metadata/*.json | sort -nr | head -n1) | duckdb
# Invalid Input Error:
# Cannot parse file header: Invalid Avro identifier
```

**Comment by kris-gaudel** [comment]
@nvartolomei What version/branch/commit was this code ran with? I ran unit and integration tests locally and it all passed for me

**Comment by nvartolomei** [comment]
@kris-gaudel I did provide all the details in the comment. I install pyiceberg as a dependency using `uv`

```
dependencies = [
    "pyiceberg-core>=0.5.1",
    "pyiceberg[pyarrow,sql-sqlite]>=0.9.1",
]
```

**Comment by kris-gaudel** [comment]
Aha sorry idk how I missed that, I thought it was an issue with my changes 😅

**Comment by kevinjqliu** [comment]
thank you for the repro @nvartolomei 
i can confirm this is still an issue on latest main branch

**Comment by kevinjqliu** [comment]
these files are created

```
warehouse
└── default
    └── nested_table
        ├── data
        │   ├── %F0%9F%98%8E=Cool+Bar
        │   │   └── 00000-1-3d042b77-ea8d-4687-82fc-956637945f82.parquet
        │   └── %F0%9F%98%8E=Cool+Foo
        │       └── 00000-0-3d042b77-ea8d-4687-82fc-956637945f82.parquet
        └── metadata
            ├── 00000-4fa0ec29-7015-4b81-8c8c-860fad7789cd.metadata.json
            ├── 00001-96e0db38-f241-4600-9c7d-7f5b8f95265b.metadata.json
            ├── 3d042b77-ea8d-4687-82fc-956637945f82-m0.avro
            └── snap-2593124689753704982-0-3d042b77-ea8d-4687-82fc-956637945f82.avro
```

duckdb can read the manifest list file, but not the manifest file
```
➜  iceberg-python git:(main) ✗ duckdb -c 'FROM read_avro("warehouse/default/nested_table/metadata/snap-2593124689753704982-0-3d042b77-ea8d-4687-82fc-956637945f82.avro")'
┌──────────────────────┬─────────────────┬───────────────────┬─────────┬───┬──────────────────┬─────────────────────┬────────────────────┬──────────────────────┬──────────────┐
│    manifest_path     │ manifest_length │ partition_spec_id │ content │ … │ added_rows_count │ existing_rows_count │ deleted_rows_count │      partitions      │ key_metadata │
│       varchar        │      int64      │       int32       │  int32  │   │      int64       │        int64        │       int64        │ struct(contains_nu…  │     blob     │
├──────────────────────┼─────────────────┼───────────────────┼─────────┼───┼──────────────────┼─────────────────────┼────────────────────┼──────────────────────┼──────────────┤
│ /Users/kevinliu/re…  │      4724       │         0         │    0    │ … │        2         │          0          │         0          │ [{'contains_null':…  │ NULL         │
├──────────────────────┴─────────────────┴───────────────────┴─────────┴───┴──────────────────┴─────────────────────┴────────────────────┴──────────────────────┴──────────────┤
│ 1 rows                                                                                                                                                  15 columns (9 shown) │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

```
➜  iceberg-python git:(main) ✗ duckdb -c 'FROM read_avro("warehouse/default/nested_table/metadata/3d042b77-ea8d-4687-82fc-956637945f82-m0.avro")'
Invalid Input Error:
Cannot parse file header: Invalid Avro identifier
```

**Comment by kevinjqliu** [comment]
pulling this back into 0.10, lets get a fix for this

**Comment by kevinjqliu** [comment]
`avro-tool` can read the manifest file. I formatted the result with vscode.


Note the:
```
        "partition": {
            "\uD83D\uDE0E": {
                "string": "Cool Foo"
            }
        },
```


```
➜  iceberg-python git:(main) ✗ avro-tools tojson warehouse/default/nested_table/metadata/3d042b77-ea8d-4687-82fc-956637945f82-m0.avro 
25/07/31 11:07:42 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

{
    "status": 1,
    "snapshot_id": {
        "long": 2593124689753704982
    },
    "sequence_number": null,
    "file_sequence_number": null,
    "data_file": {
        "content": 0,
        "file_path": "/Users/kevinliu/repos/iceberg-python/warehouse/default/nested_table/data/%F0%9F%98%8E=Cool+Foo/00000-0-3d042b77-ea8d-4687-82fc-956637945f82.parquet",
        "file_format": "PARQUET",
        "partition": {
            "\uD83D\uDE0E": {
                "string": "Cool Foo"
            }
        },
        "record_count": 1,
        "file_size_in_bytes": 891,
        "column_sizes": {
            "array": [
                {
                    "key": 1,
                    "value": 73
                },
                {
                    "key": 2,
                    "value": 94
                }
            ]
        },
        "value_counts": {
            "array": [
                {
                    "key": 1,
                    "value": 1
                },
                {
                    "key": 2,
                    "value": 1
                }
            ]
        },
        "null_value_counts": {
            "array": [
                {
                    "key": 1,
                    "value": 0
                },
                {
                    "key": 2,
                    "value": 0
                }
            ]
        },
        "nan_value_counts": {
            "array": []
        },
        "lower_bounds": {
            "array": [
                {
                    "key": 1,
                    "value": "Foo"
                },
                {
                    "key": 2,
                    "value": "Cool Foo"
                }
            ]
        },
        "upper_bounds": {
            "array": [
                {
                    "key": 1,
                    "value": "Foo"
                },
                {
                    "key": 2,
                    "value": "Cool Foo"
                }
            ]
        },
        "key_metadata": null,
        "split_offsets": {
            "array": [
                4
            ]
        },
        "equality_ids": null,
        "sort_order_id": null
    }
}
{
    "status": 1,
    "snapshot_id": {
        "long": 2593124689753704982
    },
    "sequence_number": null,
    "file_sequence_number": null,
    "data_file": {
        "content": 0,
        "file_path": "/Users/kevinliu/repos/iceberg-python/warehouse/default/nested_table/data/%F0%9F%98%8E=Cool+Bar/00000-1-3d042b77-ea8d-4687-82fc-956637945f82.parquet",
        "file_format": "PARQUET",
        "partition": {
            "\uD83D\uDE0E": {
                "string": "Cool Bar"
            }
        },
        "record_count": 1,
        "file_size_in_bytes": 891,
        "column_sizes": {
            "array": [
                {
                    "key": 1,
                    "value": 73
                },
                {
                    "key": 2,
                    "value": 94
                }
            ]
        },
        "value_counts": {
            "array": [
                {
                    "key": 1,
                    "value": 1
                },
                {
                    "key": 2,
                    "value": 1
                }
            ]
        },
        "null_value_counts": {
            "array": [
                {
                    "key": 1,
                    "value": 0
                },
                {
                    "key": 2,
                    "value": 0
                }
            ]
        },
        "nan_value_counts": {
            "array": []
        },
        "lower_bounds": {
            "array": [
                {
                    "key": 1,
                    "value": "Bar"
                },
                {
                    "key": 2,
                    "value": "Cool Bar"
                }
            ]
        },
        "upper_bounds": {
            "array": [
                {
                    "key": 1,
                    "value": "Bar"
                },
                {
                    "key": 2,
                    "value": "Cool Bar"
                }
            ]
        },
        "key_metadata": null,
        "split_offsets": {
            "array": [
                4
            ]
        },
        "equality_ids": null,
        "sort_order_id": null
    }
}
```

**Comment by kevinjqliu** [comment]
In #2264 i tried to repro the above issue with spark. duckdb is able to read the metadata produced by spark


the manifest file's `data_file.partition` is different
spark produces `_xD83D_xDE0E` while pyiceberg produces`\uD83D\uDE0E`

**Comment by kevinjqliu** [comment]
i think its exactly what @nvartolomei mentioned in https://github.com/apache/iceberg-python/issues/2123#issuecomment-2995265399

iceberg java encoding, https://github.com/apache/iceberg/blob/1bd8d5e2de56d05180030b856ce2c50c66ef1f13/core/src/main/java/org/apache/iceberg/avro/AvroSchemaUtil.java#L550-L555
pyiceberg encoding, https://github.com/apache/iceberg-python/blob/904c0b77c33768716e8672b38bae73bfcf565fbf/pyiceberg/schema.py#L1393-L1394

**Comment by kris-gaudel** [comment]
@kevinjqliu I think my PR should address this issue, as I followed the sanitization as per the Java codebase and @nvartolomei's comment

**Comment by kevinjqliu** [comment]
awesome! looking, thanks! cc @sungwy 

EDIT: this is the PR https://github.com/apache/iceberg-python/pull/2245

**Comment by kevinjqliu** [comment]
This is now fixed in #2245. Thank you everyone for the great discussion :)

**Comment by kris-gaudel** [comment]
@Fokko @kevinjqliu Thank you for the guidance! I'm interested in getting more involved with OSS, do you have any recommendations on some other issues I could take on in this project?

**Comment by kevinjqliu** [comment]
thanks for the interest @kris-gaudel. There are a lot of opportunities to help. Heres one I just found https://github.com/apache/iceberg-python/issues/2119. Please feel free to go through the issues page too
